# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title: 'Danil Zakablukovskii'
tagline: 'Home page'
description: '<p>My little own home page and blog.</p> <p>И немного русского!</p>'

url: http://danilz.me
baseurl: /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

gems: [jekyll-paginate, jekyll-gist, jekyll-watch]

# Custom vars
