# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: '@djagya'
tagline: 'Home page'
description: 'My little own home page and blog.'

url: https://danilz.me
baseurl: /

author:
  name: 'Danil Zakablukovskii'
  email: danil.kabluk@gmail.com

paginate: 10
excerpt_separator: "<!-- more -->"

gems: [jekyll-paginate, jekyll-gist, jekyll-watch]

# Custom vars
